-- Sucursales
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (1, 'Central', 'Av. Principal');
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (2, 'Sucursal Norte', 'Calle Norte');
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (3, 'Sucursal Sur', 'Calle Sur');
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (4, 'Sucursal Este', 'Av. del Este 456');
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (5, 'Sucursal Oeste', 'Av. del Oeste 789');
INSERT INTO STORE (ID, NAME, LOCATION) VALUES (6, 'Sucursal Centro Comercial', 'Shopping Central Piso 2');

-- Central (STORE_ID = 1)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (1, 'Televisor Samsung 55', 'TV', 20, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (2, 'Notebook Lenovo Thinkpad', 'Computadora', 15, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (3, 'Smartphone iPhone 14', 'Celular', 30, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (4, 'Heladera Whirlpool', 'Electrodomestico', 10, 1);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (5, 'Auriculares Sony', 'Audio', 25, 1);

-- Sucursal Norte (STORE_ID = 2)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (3, 'Smartphone iPhone 14', 'Celular', 15, 2);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (6, 'Notebook HP Pavilion', 'Computadora', 12, 2);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (1, 'Televisor Samsung 55', 'TV', 8, 2);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (7, 'Parlante JBL Charge 5', 'Audio', 18, 2);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (8, 'Consola PlayStation 5', 'Consola', 6, 2);

-- Sucursal Sur (STORE_ID = 3)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (9, 'Televisor LG 65', 'TV', 10, 3);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (10, 'Tablet Samsung Galaxy Tab', 'Tablet', 20, 3);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (4, 'Heladera Whirlpool', 'Electrodomestico', 5, 3);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (5, 'Auriculares Sony', 'Audio', 9, 3);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (11, 'Notebook Dell Inspiron', 'Computadora', 11, 3);

-- Sucursal Este (STORE_ID = 4)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (12, 'Smartphone Samsung Galaxy S23', 'Celular', 22, 4);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (13, 'Smartwatch Apple Watch 9', 'Wearable', 11, 4);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (9, 'Televisor LG 65', 'TV', 7, 4);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (14, 'Consola Xbox Series X', 'Consola', 5, 4);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (15, 'Camara Canon EOS R10', 'Fotografia', 4, 4);

-- Sucursal Oeste (STORE_ID = 5)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (16, 'Televisor TCL 50', 'TV', 14, 5);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (17, 'Heladera Samsung No Frost', 'Electrodomestico', 6, 5);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (3, 'Smartphone iPhone 14', 'Celular', 10, 5);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (7, 'Parlante JBL Charge 5', 'Audio', 12, 5);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (18, 'Nintendo Switch OLED', 'Consola', 8, 5);

-- Sucursal Centro Comercial (STORE_ID = 6)
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (8, 'Consola PlayStation 5', 'Consola', 9, 6);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (14, 'Consola Xbox Series X', 'Consola', 8, 6);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (18, 'Nintendo Switch OLED', 'Consola', 12, 6);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (15, 'Camara Canon EOS R10', 'Fotografia', 5, 6);
INSERT INTO PRODUCT (ID, NAME, CATEGORY, QUANTITY, STORE_ID) VALUES (2, 'Notebook Lenovo Thinkpad', 'Computadora', 7, 6);
