CREATE TABLE STORE (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    LOCATION VARCHAR(255)
);

CREATE TABLE PRODUCT (
    ID BIGINT,
    STORE_ID BIGINT,
    NAME VARCHAR(255),
    CATEGORY VARCHAR(255),
    QUANTITY INT,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID, STORE_ID),
    CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE(ID)
);